version: "3"
services:
  proxy:
    env_file: .env
    image: jupyterhub/configurable-http-proxy:3.1.1
    networks:
      - jupyterhub-net
    # expose the proxy to the world
    ports:
      - "80:8000"
      - "8080:8080"
    command:
      - configurable-http-proxy
      - "--error-target"
      - "http://hub/hub/error"

  hub:
    env_file: .env
    image: vasiltapkin/vasilhub:latest
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "jupyterhub_data:/data"
    networks:
      - jupyterhub-net
    ports:
      - "8080:8080"
networks:
  jupyterhub-net:
    driver: overlay
