version: "3"
services:
  hub:
    env_file: .env
    image: vasiltapkin/vasilhub:latest
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - jupyterhub-net
    ports:
      - "8080:8080"
networks:
  jupyterhub-net:
    driver: overlay
